### ISSUE TITLE
KeyError: 'content-length'

### ISSUE THREAD

**Issue by kamakazikamikaze** [NotGlop/docker-drag#17]
I am calling the script as follows:

`python docker_pull.py registry.access.redhat.com/ubi8/ubi`

The script will output the following:

`78afc5364ad2: Downloading...`

And then it fails:

```
Traceback (most recent call last):
  File "docker_pull.py", line 155, in <module>
    unit = int(bresp.headers['Content-Length']) / 50
  File "C:\Users\<NTID>\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'
```
I've made a few adjustments to your script, primarily adding the `proxies=` option for calls to `requests` functions as I'm stuck behind a proxy. This allows me to communicate with the Redhat registry. So line 155 is actually line 141 as referenced below.

https://github.com/NotGlop/docker-drag/blob/5413165a2453aa0bc275d7dc14aeb64e814d5cc0/docker_pull.py#L141

I've added a `print` statement to dump the `bresp.headers` and `Content-Length` is not in there:

```py
{
  'Accept-Ranges': 'bytes',
  'Content-Type': 'text/plain',
  'ETag': '"ced9e6d20e1ac931689399b68b0dd6a4:1588112355"',
  'Last-Modified': 'Tue, 28 Apr 2020 22:03:16 GMT',
  'Server': 'AkamaiNetStorage',
  'Vary': 'Accept-Encoding',
  'Date': 'Mon, 18 May 2020 17:57:51 GMT',
  'Transfer-Encoding': 'chunked',
  'X-Docker-Size': '-1',
  'Cache-Control': 'proxy-revalidate',
  'Connection': 'Keep-Alive',
  'Content-Encoding': 'gzip'
}
```

I've confirmed with a machine at home (different OS and no proxy) that the same error is experienced. I understand that the script relies on the Docker HTTPS API v2 so I apologize if the redhat registry is actually v1. I'm new to docker and do not know how to check for this.

**Comment by kamakazikamikaze** [comment]
For reference, the docker command with the registry endpoint is listed on the [Redhat catalog page](https://catalog.redhat.com/software/containers/detail/5c359854d70cc534b3a3784e?container-tabs=gti&gti-tabs=unauthenticated):

`docker pull registry.access.redhat.com/ubi8/ubi`

**Comment by NotGlop** [comment]
Thanks for the issue. After investigating, RedHat servers are sending chunked encoded responses (cf. the header `'Transfer-Encoding': 'chunked'` in the response that you pointed out).  
As a consequence, the `Content-Length` header is not sent by the server (this is a standard behavior from HTTP/1.1).

In the Docker script, since the `Content-Length` header is only used for printing information, you can safely replace every `bresp.headers['Content-Length']` by `len(bresp.content)`  

So, as a hotfix, if you fix those 2 lines, it should work for you:  
**Line 141:** `unit = int(len(bresp.content)) / 50`
**Line 161:** `print("\r{}: Pull complete [{}]".format(ublob[7:19], len(bresp.content)))`

I will think of a cleaner way to fix this issue in the next commit.

PS: Redhat registry supports Docker HTTPS API v2, so you should be able to download images
