### ISSUE TITLE
Re-authenticate upon token expiration

### ISSUE THREAD

**Issue by stevenwernercs** [NotGlop/docker-drag#2]
trying 

```
524$ python2  docker_pull.py "jupyter/datascience-notebook"
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Creating image structure in: tmp_datascience-notebook_latest
a48c500ed24e: Pull complete [30957448]
1e1de00ff7e1: Pull complete [841]
0330ca45a200: Pull complete [412]
471db38bcfbf: Pull complete [849]
0b4aba487617: Pull complete [162]
1bac85b3a63e: Pull complete [19696719]
245be47b44f6: Pull complete [424313]
ef168d10cf08: Pull complete [666]
3f40baab49e8: Pull complete [1891]
1074310668a8: Pull complete [6005]
acab6d938518: Pull complete [147]
d3c413e667b9: Pull complete [72063649]
63b84d46215a: Pull complete [11195]
e2aa43484a2e: Pull complete [93156146]
e45a3ec35504: Pull complete [2160]
b91bbc043eab: Pull complete [434]
8842220992fc: Pull complete [691]
fc8f34d51deb: Pull complete [1006]
5f6edb450186: Pull complete [1015]
44257488fae5: Pull complete [824729788]
540df7774880: Pull complete [71414708]
178f3a1a18b4: Pull complete [271621569]
03528a45986d: Pull complete [456599]
5c52a47b5569: Pull complete [10279]
1f67b31a20f8: Pull complete [17277944]
70de4b41273e: Pull complete [171]
Traceback (most recent call last):
  File "docker_pull.py", line 86, in <module>
    file.write(unzLayer.read())
  File "/usr/lib/python2.7/gzip.py", line 261, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 303, in _read
    self._read_gzip_header()
  File "/usr/lib/python2.7/gzip.py", line 197, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file


```

**Comment by NotGlop** [comment]
Can you try it again ? I have just updated the script to add verbosity when failing to download a layer.
This may confirm what I think is the issue.

I believe you have received a bad HTTP response as I see the log in your post:
> 70de4b41273e: Pull complete [171]

This layer is not 171 bytes, as you can see from the manifest:
```
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 96304898,
         "digest": "sha256:70de4b41273ea30a20371fc037ab520f9040ba3890111a5b19d0b15f0c46e2c0"
      },

```

However, I think I know what may be the issue: since it is a big image, if you have a slow connection, your session may timeout while you download your image (have a look at the **Content-Length: 171**):

```
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:jupyter/datascience-notebook:pull",error="invalid_token"
Date: Wed, 19 Jun 2019 16:11:57 GMT
Content-Length: 171
Connection: close
Strict-Transport-Security: max-age=31536000

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"jupyter/datascience-notebook","Action":"pull"}]}]}
```

I will try to propose a fix (by renewing the session when it times out).

**Comment by NotGlop** [comment]
This has been finally fixed in commit https://github.com/NotGlop/docker-drag/commit/5bf523760dc010d11cfaa9a0065d082bec09e413.
Thanks for the issue.
