### ISSUE TITLE
Downloading container image from Azure Container Registry

### ISSUE THREAD

**Issue by as9333** [NotGlop/docker-drag#36]
Hello,

I am trying to download a container image from my azure container registry. The azure container registry has username and password authentication.  

But I am facing the below error.
```
Traceback (most recent call last):
  File "/home/user/docker_pull.py", line 72, in <module>
    auth_head = get_auth_head('application/vnd.docker.distribution.manifest.v2+json')
  File "/home/user/docker_pull.py", line 54, in get_auth_head
    access_token = resp.json()['token']
KeyError: 'token'
```

**Comment by NotGlop** [comment]
Will add auth support in a future commit. Followed in #24
